version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
            - 9229:9229
        volumes:
            - .:/app
            - '/app/node_modules'
        depends_on:
            mysql_server:
                condition: service_healthy

    mysql_server:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=test_db
            - MYSQL_USER=test_user
            - MYSQL_PASSWORD=secret
            - MYSQL_ROOT_PASSWORD=secret
        healthcheck:
            test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
            timeout: 5s
            retries: 10
